version: "3"
  
services: 
    outsider:
        build: 
            context: ./image
        image: base-image
        container_name: outsider-10.9.0.5
        tty: true
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5
        command: bash -c "
                      ip route add 172.16.10.0/24 via 10.9.0.254 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "
    inner:
        build: 
            context: ./image
        image: base-image
        container_name: inner-172.16.10.100
        tty: true
        cap_add:
            - ALL
        networks:
            net-172.16.10.0:
                ipv4_address: 172.16.10.100
        command: bash -c "
                      ip route del default &&
                      ip route add default via 172.16.10.10 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "
    apache1:
        build: 
            context: ./apache
        image: apache-image
        container_name: iweb-172.16.10.110
        tty: true
        cap_add:
            - ALL
        networks:
            net-172.16.10.0:
                ipv4_address: 172.16.10.110
        command: bash -c "
                      ip route del default &&
                      ip route add default via 172.16.10.10 &&
                      service apache2 start &&
                      tail -f /dev/null
                "
    apache2:
        build: 
            context: ./apache
        image: apache-image
        container_name: badsite-10.9.0.10
        tty: true
        cap_add:
            - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.10
        command: bash -c "
                      ip route del default &&
                      ip route add 172.16.10.0/24 via 10.9.0.254 &&
                      service apache2 start &&
                      tail -f /dev/null
                "
    router:
        build:
            context: ./image
        image: router-image
        container_name: router
        tty: true
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.254
            net-172.16.10.0:
                ipv4_address: 172.16.10.10
        command: bash -c "
                      ip route del default &&
                      ip route add default via 10.9.0.1 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null
                 "

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
    net-172.16.10.0:
        name: net-172.16.10.0
        ipam:
            config:
                - subnet: 172.16.10.0/24
